name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-and-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: chmod
      run: cd cpp && chmod +x ./configure
    - name: configure
      run: cd cpp && ./configure
    - name: make
      run: cd cpp && make
    - name: make test
      run: cd cpp && make test
